spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bloq
    username: postgres
    password: postgres
  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8090